language: node_js

node_js:
  - 10.15.1

cache:
  directories:
    - node_modules

script:
  # Run tests and generate code coverage reports
  - yarn test:coverage

notifications:
  # Default email notification settings
  email:
    on_failure: always
    on_success: change
